#baseUrl is set via HUGO_BASEURL environment variable
languageCode = "en"
#title = "2025 Christmas Tree Pickup"
title = "Annual Christmas Tree Pickup"
theme = "soho"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
pagination.pageSize = 5
ignoreErrors = ["error-remote-getjson"]
publishDir = "../public"

[params]
#title = "2025 Christmas Tree Pickup"
title = "Annual Christmas Tree Pickup"
description = "Pembroke Troop 105"
# gravatar = "soho@example.com"
images = ["profile-tree.png"]
profilePicture = "tree-drive-square.png"
copyright = "Pembroke Troop 105"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]
facebook_url = "https://www.facebook.com/share/19RkuMqnuC/?mibextid=LQQJ4d"
facebook_title = "Troop 105 Annual Tree Pickup"

## Set custom theme color.
# themeColor = "#fc2803"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true
    disabled = false
    enableDNT = true
    simple = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
      unsafe = true
